name       : vapoursynth
version    : '53'
release    : 29
source     :
    - https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R53.tar.gz : 78e2c5311b2572349ff7fec2e16311e9e4f6acdda78673872206ab660eadf7c8
license    :
    - LGPL-2.1-or-later
    - OFL-1.1
component  : multimedia.library
summary    : A video processing framework with simplicity in mind
description: |
    A video processing framework with simplicity in mind.
libsplit   : no
builddeps  :
    - pkgconfig(Magick++)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(python3)
    - pkgconfig(zimg)
    - cython
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/vapoursynth.xml -t $installdir/usr/share/mime/packages/
