name       : vapoursynth
version    : '42.1'
release    : 10
source     :
    - https://github.com/vapoursynth/vapoursynth/archive/R42.1.tar.gz : 2da653c3956d6e61b2232975ebad7e060c717ad09b08d09694e4bb4eab64f8a7
license    : LGPL-2.1
component  : programming
summary    : A video processing framework with simplicity in mind
description: |
    A video processing framework with simplicity in mind
libsplit   : no
builddeps  :
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(Magick++)
    - pkgconfig(python3)
    - pkgconfig(zimg)
    - cython
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/vapoursynth.xml -t $installdir/usr/share/mime/packages/
