name       : vapoursynth
version    : '58'
release    : 36
source     :
    - https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R58.tar.gz : 19c1169eba61d7044354da3247a3a7c02a058220054ef2a8f501bfac5fed3bfc
license    :
    - LGPL-2.1-or-later
    - OFL-1.1
component  : multimedia.library
summary    : A video processing framework with simplicity in mind
description: |
    A video processing framework with simplicity in mind.
libsplit   : no
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(zimg)
    - cython
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/vapoursynth.xml -t $installdir/usr/share/mime/packages/
