name       : vapoursynth
version    : '52'
release    : 25
source     :
    - https://github.com/vapoursynth/vapoursynth/archive/R52.tar.gz : 4d5dc7950f4357da695d29708bc98013bc3e0bd72fc5d697f8c91ce3c4a4b2ac
license    :
    - LGPL-2.1-or-later
    - OFL-1.1
component  : multimedia.library
summary    : A video processing framework with simplicity in mind
description: |
    A video processing framework with simplicity in mind.
libsplit   : no
builddeps  :
    - pkgconfig(Magick++)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(python3)
    - pkgconfig(zimg)
    - cython
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/vapoursynth.xml -t $installdir/usr/share/mime/packages/
