name       : vapoursynth
version    : '40'
release    : 6
source     :
    - https://github.com/vapoursynth/vapoursynth/archive/R40.tar.gz : a5e4260abff95c4bf33cc7ff3203e8001f7b3be7bb5ccc3a6fc2b18523823e50
license    : LGPL-2.1
component  : programming
summary    : A video processing framework with simplicity in mind
description: |
    A video processing framework with simplicity in mind
libsplit   : no
builddeps  :
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(Magick++)
    - pkgconfig(python-3.5)
    - pkgconfig(zimg)
    - cython
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
